package com.pik.contact.gui.selenium.test;
// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
public class SearchingTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void searchingcontact() {
        driver.get("http://localhost:8080/contact//contact/");
        driver.manage().window().setSize(new Dimension(1358, 728));
        driver.findElement(By.id("filter")).click();
        driver.findElement(By.id("filter")).click();
        driver.findElement(By.id("filter")).sendKeys("John");
        assertThat(driver.getTitle(), is("Contact"));
        assertThat(driver.findElement(By.cssSelector(".navbar > .col-xs-12:nth-child(1)")).getText(), is("Contact List"));
        driver.findElement(By.cssSelector("html")).click();
    }
    @Test
    public void searchingInvalidName() {
        driver.get("http://localhost:8080/contact/");
        driver.manage().window().setSize(new Dimension(1358, 728));
        driver.findElement(By.id("filter")).click();
        driver.findElement(By.id("filter")).click();
        driver.findElement(By.id("filter")).click();
        {
            WebElement element = driver.findElement(By.id("filter"));
            Actions builder = new Actions(driver);
            builder.doubleClick(element).perform();
        }
        driver.findElement(By.id("filter")).click();
        driver.findElement(By.id("filter")).click();
        driver.findElement(By.id("filter")).click();
        driver.findElement(By.id("filter")).click();
        driver.findElement(By.id("filter")).click();
        driver.findElement(By.id("filter")).sendKeys("saskalsjdlaksjdlaksjdlkksksksksksksksk");
        driver.findElement(By.cssSelector("html")).click();
        driver.findElement(By.cssSelector("html")).click();
        {
            WebElement element = driver.findElement(By.cssSelector("html"));
            Actions builder = new Actions(driver);
            builder.doubleClick(element).perform();
        }
        driver.findElement(By.id("filter")).click();
        driver.findElement(By.id("filter")).sendKeys("saskalsjdlaksjdlaksjdlkkskskskskskskskkskskskskskskskllakskskskskskdjdksjd");
        driver.findElement(By.cssSelector(".navbar")).click();
        driver.findElement(By.cssSelector(".navbar")).click();
        driver.findElement(By.cssSelector("html")).click();
        driver.findElement(By.cssSelector("html")).click();
        driver.findElement(By.id("filter")).click();
        driver.findElement(By.id("filter")).click();
        {
            WebElement element = driver.findElement(By.id("filter"));
            Actions builder = new Actions(driver);
            builder.doubleClick(element).perform();
        }
        driver.findElement(By.id("filter")).click();
        driver.findElement(By.id("filter")).sendKeys("saskalsjdlaksjdlaksjdlkkskskskskskskskkskskskskskskskllakskskskskskdjdksjdsnd nf d ndmsndf nsmasdm,nqwerqweasdasdmsmsmsndmsmdnsmdnsmsndmsndmsndmsndmsndmsdnsmdnsmdnsmndsmdn");
        driver.findElement(By.cssSelector(".navbar")).click();
        driver.findElement(By.id("filter")).click();
        driver.findElement(By.id("filter")).click();
        {
            WebElement element = driver.findElement(By.id("filter"));
            Actions builder = new Actions(driver);
            builder.doubleClick(element).perform();
        }
        driver.findElement(By.id("filter")).click();
        driver.findElement(By.id("filter")).click();
        driver.findElement(By.id("filter")).click();
        driver.findElement(By.id("filter")).sendKeys("saskalsjdlaksjdlaksjdlkkskskskskskskskkskskskskskskskllakskskskskskdjdksjdsnd nf d ndmsndf nsmasdmasasdnqwerqweasdasdmsmsmsndmsmdnsmdnsmsndmsndmsndmsndmsndmsdnsmdnsmdnsmndsmdn");
        driver.findElement(By.cssSelector("html")).click();
        driver.findElement(By.cssSelector("html")).click();
        {
            WebElement element = driver.findElement(By.cssSelector("html"));
            Actions builder = new Actions(driver);
            builder.doubleClick(element).perform();
        }
        driver.findElement(By.cssSelector("html")).click();
        driver.findElement(By.cssSelector("html")).click();
        driver.findElement(By.cssSelector("html")).click();
        {
            WebElement element = driver.findElement(By.cssSelector("html"));
            Actions builder = new Actions(driver);
            builder.doubleClick(element).perform();
        }
        driver.findElement(By.cssSelector("html")).click();
        driver.findElement(By.cssSelector("html")).click();
        driver.findElement(By.cssSelector("html")).click();
        driver.findElement(By.cssSelector("html")).click();
        driver.findElement(By.cssSelector("html")).click();
        driver.findElement(By.cssSelector("html")).click();
        driver.findElement(By.cssSelector("html")).click();
        driver.findElement(By.cssSelector("html")).click();
        driver.findElement(By.cssSelector("html")).click();
        driver.findElement(By.cssSelector("html")).click();
        driver.findElement(By.cssSelector("html")).click();
        driver.findElement(By.cssSelector("html")).click();
        driver.findElement(By.cssSelector("html")).click();
        driver.findElement(By.cssSelector("html")).click();
        driver.findElement(By.cssSelector("html")).click();
        driver.findElement(By.cssSelector("html")).click();
        driver.findElement(By.cssSelector("html")).click();
        driver.findElement(By.cssSelector("html")).click();
        driver.findElement(By.cssSelector("html")).click();
        driver.findElement(By.cssSelector("html")).click();
        driver.findElement(By.cssSelector("html")).click();
        driver.findElement(By.cssSelector("html")).click();
        driver.findElement(By.cssSelector("html")).click();
        driver.findElement(By.id("filter")).click();
        driver.findElement(By.id("filter")).click();
        {
            WebElement element = driver.findElement(By.id("filter"));
            Actions builder = new Actions(driver);
            builder.doubleClick(element).perform();
        }
        driver.findElement(By.id("filter")).click();
        driver.findElement(By.id("filter")).sendKeys("Diana");
        driver.findElement(By.cssSelector(".cards")).click();
        driver.findElement(By.cssSelector(".cards")).click();
        {
            WebElement element = driver.findElement(By.cssSelector(".cards"));
            Actions builder = new Actions(driver);
            builder.doubleClick(element).perform();
        }
        driver.findElement(By.id("filter")).click();
        driver.findElement(By.id("filter")).sendKeys("Dianassss");
    }
}
